executable            = /afs/cern.ch/user/n/nminafra/Work/TimingKU/TimingAnalysisOscApril/run_selected2.sh
arguments             = $(ProcId)
output                = /afs/cern.ch/user/n/nminafra/Work/TimingKU/TimingAnalysisOscApril/Condor/Logs/run_$(ProcId).out
error                 = /afs/cern.ch/user/n/nminafra/Work/TimingKU/TimingAnalysisOscApril/Condor/Logs/run_$(ProcId).err
log                   = /afs/cern.ch/user/n/nminafra/Work/TimingKU/TimingAnalysisOscApril/Condor/Logs/run_$(ProcId).log

request_cpus = 1
+JobFlavour = "workday"
+Requirements           = OpSysAndVer =?= "SLCern6"


queue 3
